import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';
import prettierConfig from 'eslint-config-prettier';

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const eslintConfig = [
  // next-env.d.ts is regenerated by Next.js and explicitly marked
  // "should not be edited" - never worth linting or auto-fixing.
  { ignores: ['.next/**', 'node_modules/**', 'coverage/**', 'next-env.d.ts'] },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  // Last: turns off any stylistic rule that would otherwise fight Prettier.
  prettierConfig,
];

export default eslintConfig;
