import type {
  AskResponse,
  ChunkExcerpt,
  Citation,
  RepositorySummary,
  SearchResponse,
} from '@app/shared';

/**
 * Plain-text renderings of API results for an LLM client. Kept pure so every
 * output a model will read is easy to test and change in one place.
 */

/**
 * A fenced code block that can't be broken by the code itself: the fence is
 * always longer than the longest run of backticks in the content.
 */
export function codeFence(content: string, language = ''): string {
  const longestRun = Math.max(0, ...(content.match(/`+/g) ?? []).map((run) => run.length));
  const fence = '`'.repeat(Math.max(3, longestRun + 1));
  return `${fence}${language}\n${content}\n${fence}`;
}

export function location(
  item: Pick<Citation, 'path' | 'startLine' | 'endLine' | 'symbol'>,
): string {
  const symbol = item.symbol ? ` (${item.symbol})` : '';
  return `${item.path}:${item.startLine}-${item.endLine}${symbol}`;
}

export function formatRepository(repo: RepositorySummary): string {
  const base = `${repo.name} [${repo.status}] id=${repo.id}`;
  if (repo.status === 'INDEXED') {
    return `${base} - ${repo.fileCount} files, ${repo.chunkCount} chunks, commit ${repo.revision.slice(0, 7)}`;
  }
  if (repo.status === 'FAILED') return `${base} - ${repo.error ?? 'indexing failed'}`;
  return base;
}

export function formatRepositoryList(repositories: RepositorySummary[]): string {
  if (repositories.length === 0) {
    return 'No repositories have been indexed yet. Use index_repository with a public GitHub URL.';
  }
  const ready = repositories.filter((r) => r.status === 'INDEXED').length;
  return [
    `${repositories.length} repositories (${ready} ready to query):`,
    ...repositories.map((r) => `- ${formatRepository(r)}`),
  ].join('\n');
}

export function formatAnswer(repo: RepositorySummary, response: AskResponse): string {
  const sources = response.citations.map(
    (c, i) => `[${i + 1}] ${location(c)} chunk=${c.chunkId} score=${c.score}`,
  );
  return [
    `Answer about ${repo.name} (generated by the assistant's own LLM from retrieved code):`,
    '',
    response.answer,
    '',
    sources.length > 0 ? 'Sources retrieved:' : 'No source code was retrieved for this question.',
    ...sources,
  ].join('\n');
}

export function formatSearchResults(
  repo: RepositorySummary,
  query: string,
  response: SearchResponse,
): string {
  if (response.results.length === 0) {
    return `No code in ${repo.name} matched "${query}".`;
  }
  const hits = response.results.map((hit, i) =>
    [
      `## [${i + 1}] ${location(hit)} - score ${hit.score}, chunk ${hit.chunkId}`,
      codeFence(hit.content, hit.language),
    ].join('\n'),
  );
  return [
    `${response.results.length} code chunks from ${repo.name} for "${query}", most relevant first:`,
    '',
    hits.join('\n\n'),
  ].join('\n');
}

export function formatExcerpt(repo: RepositorySummary, excerpt: ChunkExcerpt): string {
  return [`${repo.name} - ${location(excerpt)}`, codeFence(excerpt.content, excerpt.language)].join(
    '\n',
  );
}
